#%RAML 1.0
title: My API with Types
mediaType: application/json
baseUri: http://raml-test.domain.com
types:
  Org:
    type: object
    properties:
      onCall: Alertable # inherits all properties from type `Alertable`
      Head: Manager # inherits all properties from type `Manager`
  Person:
    type: object
    properties:
      firstname: string
      lastname: string
      title?: string
    example:
      firstname: Pawel
      lastname: Psztyc
      title: Mr
  Phone:
    type: string
    pattern: "^[0-9|-]+$" # defines pattern for the content of type `Phone`
  Manager:
    type: Person # inherits all properties from type `Person`
    properties:
      reports: Person[] # inherits all properties from type `Person`; array type where `[]` is a shortcut
      phone:  Phone
  Admin:
    type: Person # inherits all properties from type `Person`
    properties:
      clearanceLevel:
        enum: [ low, high ]
  AlertableAdmin:
    type: Admin # inherits all properties from type `Admin`
    properties:
      phone: Phone # inherits all properties from type `Phone`; uses shortcut syntax
  Alertable: Manager | AlertableAdmin # union type; either a `Manager` or `AlertableAdmin`
securitySchemes:
  basic:
    type: Basic Authentication
    description: Authenticate!
/people:
  displayName: People endpoint
  get:
    displayName: List people
    responses:
      200:
        body:
          application/json:
            type: Person[]
  post:
    body:
      application/json:
        type: object
        properties:
          id: number
          name: string
  put:
    body:
      application/json:
        type: Person
/{orgId}:
  securedBy: basic
  put:
    body:
      application/json:
        type: Org
  get:
    queryParameters:
      test:
        type: string
        default: test
        example: test
      optional:
        type: string
        required: false
        example: optional-test
    responses:
      200:
        body:
          application/json:
            type: Org # reference to global type definition
            example:
              onCall:
                firstname: nico
                lastname: ark
                clearanceLevel: low
                phone: "12321"
              Head:
                firstname: nico
                lastname: ark
                reports:
                  -
                    firstname: nico
                    lastname: ark
                phone: "123-23"
